### PR TITLE
[MLU] add output defs 4 mlu

### PR DESCRIPTION
**Pull request by piDack**
For more info about pr change, please click [it](https://github.com/PaddlePaddle/PaddleCustomDevice/issues/435).

### CODE REVIEW

**Comment by piDack** [comment]
Hi @ShawnNew, Please review this PR.The background of modifying is [issue#435](https://github.com/PaddlePaddle/PaddleCustomDevice/issues/435).

**Comment by ShawnNew** [comment]
> Hi @ShawnNew, Please review this PR.The background of modifying is [issue#435](https://github.com/PaddlePaddle/PaddleCustomDevice/issues/435).

Have UTs all passed?

**Review by ShawnNew — APPROVED** [review]
LGTM

**Comment by piDack** [comment]
> > Hi @ShawnNew, Please review this PR.The background of modifying is [issue#435](https://github.com/PaddlePaddle/PaddleCustomDevice/issues/435).
> 
> Have UTs all passed?

yep

**Pull request merged**
